---
title: "PSTAT 120B: Mathematical Statistics"
subtitle: "Ethan's Week 2 Discussion Section"
footer: "PSTAT 120B - Winter 2026 with Dr. Annie Qu; material © Ethan P. Marzban"
logo: "Images/120b_logo.svg"
format: 
  clean-revealjs:
    theme: ../slides.scss
    transition: fade
    slide-number: true
    incremental: true 
    chalkboard: true
    menu:
      side: left
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Ethan P. Marzban
    affiliations: Department of Statistics and Applied Probability; UCSB <br /> <br />
institute: January 14, 2026
title-slide-attributes:
    data-background-image: "Images/120b_logo.svg"
    data-background-size: "30%"
    data-background-opacity: "0.5"
    data-background-position: 80% 50%
code-annotations: hover
---

<style>
mjx-math {
  font-size: 80% !important;
}
</style>

<script>
MathJax = {
  options: {
    menuOptions: {
      settings: {
        assistiveMml: false
      }
    }
  }
};
</script>
<script type="text/javascript" id="MathJax-script" async src="path-to-MathJax/tex-chtml.js"></script>


$$
\newcommand\R{\mathbb{R}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\S}{\mathbb{S}}
\newcommand{\Prob}{\mathbb{P}}
\newcommand{\F}{\mathcal{F}}
\newcommand{\1}{1\!\!1}
\newcommand{\comp}[1]{#1^{\complement}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\SD}{\mathrm{SD}}
\newcommand{\vect}[1]{\vec{\boldsymbol{#1}}}
\newcommand{\tvect}[1]{\vec{\boldsymbol{#1}}^{\mathsf{T}}}
\newcommand{\hvect}[1]{\widehat{\boldsymbol{#1}}}
\newcommand{\mat}[1]{\mathbf{#1}}
\newcommand{\tmat}[1]{\mathbf{#1}^{\mathsf{T}}}
\newcommand{\Cov}{\mathrm{Cov}}
\DeclareMathOperator*{\argmin}{\mathrm{arg} \ \min}
\newcommand{\iid}{\stackrel{\mathrm{i.i.d.}}{\sim}}
$$

```{css echo = F}
.hscroll {
  height: 100%;
  max-height: 600px;
  max-width: 2000px;
  overflow: scroll;
}
```

```{r setup, echo = F}
library(tidyverse)
library(countdown)
library(fixest)
library(modelsummary) # Make sure you have >=v2.0.0
library(GGally)
library(ggokabeito)
library(reshape2)
library(pander)
library(gridExtra)
library(cowplot)
library(palmerpenguins)
library(plotly)
library(tidymodels)
```

## {{< fa square-root-variable >}} Transformations
### Univariate Case

::: {.callout-tip}
## **Goal**

Given a random variable _X_ whose distribution is known, what is the distribution of _Y_ := _g_(_X_) for some function _g_(•)?
:::

-   **Real-World Example:** Unit conversion
    -   Let _X_ denote temperature measurements of some apparatus in Centigrade
    -   Let _Y_ denote the temperature measurements in _Fahrenheit_
    -   _Y_ = (9/5)*X* + 32
    
-   Expectation (sidebar: how can we compute $\E[Y]$?) is not enough
    -   E.g. just because, say, $\E[Y] = 2$ doesn't mean we know what _distribution_ _Y_ follows
    
    
## {{< fa square-root-variable >}} Transformations
### MGF Method

::: {.callout-tip}
## **Goal**

Given a random variable _X_ whose distribution is known, what is the distribution of _Y_ := _g_(_X_) for some function _g_(•)?
:::

-   **First Approach:** Leverage the fact that MGF's uniquely determine distributions
    -   That is, if we can find the MGF _M_~_Y_~(_t_) of _Y_, then we will (hopefully!) know its distribution!
    
-   Recall two useful properties of MGFs from last week's Section:
    1)    If _X_ and _Y_ are independent, _M_<sub>_X_ + _Y_</sub>(_t_) = _M_~_X_~(_t_) * _M_~_Y_~(_t_) 
    2)    M<sub>_a_*X* + _b_</sub>(_t_) = _e_<sup>_b_*t*</sup> * M~_X_~(_a_*t*)
    
    

## {{< fa square-root-variable >}} Transformations
### MGF Method: Example (On the Board)

::: {.callout-tip}
## **Example 1**

If _X_ ~ Exp(_λ_) and _Y_ = _c_*X* for some _c_ > 0, what is the distribution of _Y_?
:::



## {{< fa square-root-variable >}} Transformations
### Transformation Theorem

::: {.callout-important}
## **Transformation Theorem**

If _Y_ = _g_(_X_) for some monotonic and differentiable _g_(•), then $f_Y(y) = f_X(g^{-1}(y)) \cdot \left| \frac{\mathrm{d}}{\mathrm{d}y} g^{-1}(y) \right|$
:::

::: {.fragment}
::: {.callout-tip}
## **Example 1 (Revisited)**

If _X_ ~ Exp(_λ_) and _Y_ = _c_*X* for some _c_ > 0, what is the distribution of _Y_?
:::
:::





## {{< fa square-root-variable >}} Transformations
### Transformation Theorem

::: {.callout-important}
## **Transformation Theorem**

If _Y_ = _g_(_X_) for some monotonic and differentiable _g_(•), then $f_Y(y) = f_X(g^{-1}(y)) \cdot \left| \frac{\mathrm{d}}{\mathrm{d}y} g^{-1}(y) \right|$
:::

-   If _g_(•) is **not** monotonic, then split up the support of _X_ into regions over which _g_(•) *is* monotonic.


::: {.fragment}
::: {.callout-tip}
## **Example 2**

If _X_ ~ Unif[-1, 1] and _Y_ := _X_^2^, find _f_~_Y_~(_y_), the density of _Y_.
:::
:::

::: {.fragment}
**_Try this on your own!_** The final answer is $f_Y(y) = \begin{cases} \frac{1}{2 \sqrt{y}} & \text{if } 0 \leq y \leq 1 \\ 0 & \text{otherwise} \\ \end{cases}$
:::


